"""
Rule engine for source -> target-master data migration.

Deliberately kept free of any Streamlit/UI code so it can be unit tested
and reused (e.g. from a CLI batch script) independently of the app.

Rule types (this is the actual vocabulary of the SOP document, not a
generic "ETL mapping DSL" — each type maps to one concrete instruction
pattern seen in Instruction_for_master_data_rtf.doc):

  skip              -> column left blank in output. Use for fields the
                        SOP says "ফাঁকা থাকবে" (stays blank).
  constant          -> same literal value on every row. Use for fields
                        the SOP fixes for the whole batch (AssessmentType=1,
                        ApproveStatus=2, dates, etc).
  copy              -> straight copy from a source column, no fallback.
  copy_default      -> copy from a source column, but substitute a
                        default when the source is blank/missing. This is
                        the SOP's "প্রাপ্ত ডাটা থেকে বসাতে হবে, না থাকলে X বসাতে
                        হবে" pattern (father name -> "অজানা", mobile -> "0",
                        rent/area fields -> "0.00", etc). If no source
                        column is chosen, this degrades to a pure constant.
  equals_column     -> value equals another TARGET column's already-computed
                        value. Used for AnnualValuation=FinalValuation,
                        TaxOnAnnualValuation=TaxOnFinalValuation,
                        InstallmentStartFinancialYearId=ReassessmentYear.
  batch_id          -> single Id value, same for every row in this run,
                        looked up ONCE by a human from a separate reference
                        file (ZoneInfoId, Fiscal Year Id, IUser number).
                        The tool does not resolve these automatically --
                        the SOP explicitly says these come from separate
                        Red-Marked reference files per pourashava.
  lookup_id         -> per-row FK resolution: raw source text matched
                        against an uploaded (Id, Label) lookup table.
                        WardId, PropertyUseId, PropertyTypeId, TaxPayerTypeId.
  generated_sequence-> a numeric sequence generated by the tool, e.g. the
                        target system's Id column (starting from a
                        user-supplied "current max Id + 1", since that's
                        only knowable from the live DB, not from this file).
  sms_account_number-> the specific SMSAccountNumber algorithm from the SOP:
                        concat(pourashava_code, "01", row_sequence_number),
                        unique and sequential, no padding on the sequence part.
  manual_external   -> field requires a process OUTSIDE this tool per the
                        SOP (StreetId needs a PRM_Street DB import + filter
                        + manual eyeballing; BankAccountInfoId needs bank
                        records created in the live DB first). The tool
                        will copy a source column IF you've already done
                        that external step and pasted the resolved Ids
                        back into your source file -- it will not pretend
                        to do the DB round-trip itself.
"""

from dataclasses import dataclass, field
from typing import Optional
import re
import unicodedata

import pandas as pd

RULE_TYPES = [
    "skip", "constant", "copy", "copy_default", "equals_column",
    "batch_id", "lookup_id", "generated_sequence", "sms_account_number",
    "manual_external", "client_id",
]


def normalize(s):
    """NFC-normalize + collapse whitespace. Guards against the
    composed-vs-decomposed Bengali unicode bug causing silent match
    failures (a known recurring issue in this project's other pipelines)."""
    if s is None:
        return ""
    s = str(s)
    s = unicodedata.normalize("NFC", s)
    return re.sub(r"\s+", " ", s).strip()


_BN_DIGITS = str.maketrans("০১২৩৪৫৬৭৮৯", "0123456789")


def normalize_digits(s):
    """Convert Bengali digits to English digits and strip leading zeros.
    Purpose-built for messy hand-typed numeric CODES like Ward No., where
    the same source file mixes '1', '০৪', '৩', and even malformed hybrids
    like '০6' for what should be a single-digit ward number. This is an
    OPTIONAL extra normalization pass (on top of normalize()) -- it is
    not applied by default because it would be wrong to silently strip
    leading zeros from a field where they're meaningful (e.g. a real
    zero-padded code). Callers opt in explicitly."""
    if s is None:
        return ""
    s = normalize(s).translate(_BN_DIGITS)
    s = s.lstrip("0") or "0"
    return s


def translate_bn_digits(s):
    """Convert Bengali digits to English digits WITHOUT stripping leading
    zeros or otherwise reformatting -- for fields like HoldingNo that may
    contain slashes ('480/1') or meaningful leading zeros, where you want
    the digit script fixed but nothing else touched."""
    if s is None:
        return s
    return normalize(s).translate(_BN_DIGITS)


def numeric_clean(s):
    """Strip %, commas, currency symbols, stray whitespace from a
    hand-typed numeric-looking value, and translate any Bengali digits
    to English (a numeric field has no legitimate reason to keep them).
    Does not attempt currency/locale conversion -- just removes/fixes
    characters that break float()/downstream numeric handling."""
    if s is None:
        return s
    s = str(s)
    s = unicodedata.normalize("NFC", s).translate(_BN_DIGITS)
    s = s.replace(",", "").replace("%", "").strip()
    return s


@dataclass
class Rule:
    type: str = "skip"
    source_col: Optional[str] = None
    value: Optional[str] = None            # constant value / default value / batch_id value / equals-column target name
    numeric_clean: bool = False
    convert_bn_digits: bool = False
    seq_start: int = 1
    seq_pad: int = 0
    seq_prefix: str = ""
    sms_code: str = ""
    sms_branch: str = "01"
    note: str = ""
    # client_id (ClientNo = ward-street-holding) params. Each part is
    # independently configurable because the SOURCE format for ward/street
    # codes genuinely differs pourashava to pourashava (sometimes the raw
    # source column already IS the human code; sometimes you only have a
    # DB Id and need an Id->Code lookup table to translate it).
    cid_ward_mode: str = "source_column"     # "source_column" | "lookup_code"
    cid_ward_source: Optional[str] = None    # source column name, OR target column name (e.g. "WardId") if mode=lookup_code
    cid_street_mode: str = "source_column"
    cid_street_source: Optional[str] = None
    cid_holding_mode: str = "source_column"
    cid_holding_source: Optional[str] = None
    cid_pad_width: int = 2
    cid_separator: str = "-"


def find_col(df: pd.DataFrame, source_col: str):
    """Resolve a stored source_col name to the actual df column, tolerant
    of NFC vs decomposed Unicode mismatches -- e.g. a mapping saved in a
    JSON config on one run, reloaded against a freshly-read Excel file
    whose Bengali headers happen to decode with different codepoint
    composition. Exact match first (fast path), NFC-normalized fallback.
    Returns None if truly not found -- caller must handle that as missing,
    not silently pick a wrong column."""
    if source_col is None:
        return None
    if source_col in df.columns:
        return source_col
    target = normalize(source_col)
    for c in df.columns:
        if normalize(c) == target:
            return c
    return None


def format_code_part(raw, pad_width):
    """Normalize to English digits and zero-pad to a MINIMUM width
    (zfill never truncates, so a 3-digit holding number stays 3 digits
    even with pad_width=2 -- matches 'at least two digits' requirement).
    Returns (formatted_value_or_None, is_clean_numeric)."""
    if raw is None or (isinstance(raw, float) and pd.isna(raw)) or str(raw).strip() == "":
        return None, True
    d = normalize_digits(raw)
    if d.isdigit():
        return d.zfill(pad_width), True
    return d, False  # non-numeric leftover after digit translation -- pass through but flag


def apply_rules(df: pd.DataFrame, target_columns: list, rules: dict, lookup_value_maps: dict, code_lookups: dict = None):

    """
    df: source dataframe
    target_columns: ordered list of target schema column names
    rules: {target_col: Rule}
    lookup_value_maps: {target_col: {normalized_source_value: chosen_id_str}}
    code_lookups: {target_col: {id_str: code_str}} -- Id-to-human-Code
    tables used by client_id rules in "lookup_code" mode (e.g. resolving
    an already-computed WardId FK back to its 2-digit ward code).

    Returns (output_df, audit) where audit is a dict of per-column stats
    plus a top-level 'validation' list of SOP-specific warnings.
    """
    code_lookups = code_lookups or {}
    n = len(df)
    out = pd.DataFrame(index=df.index)
    audit = {"columns": {}, "validation": []}

    deferred_equals = []
    deferred_client_id = []

    for tc in target_columns:
        r = rules.get(tc, Rule())
        col_audit = {"rule_type": r.type, "filled": 0, "defaulted": 0, "unmapped": 0}

        if r.type == "skip":
            out[tc] = None

        elif r.type == "constant":
            out[tc] = r.value if r.value is not None else ""
            col_audit["filled"] = n

        elif r.type == "copy":
            actual_col = find_col(df, r.source_col)
            if actual_col:
                vals = df[actual_col]
                if r.numeric_clean:
                    vals = vals.map(lambda v: numeric_clean(v) if pd.notna(v) else v)
                if r.convert_bn_digits:
                    vals = vals.map(lambda v: translate_bn_digits(v) if pd.notna(v) else v)
                out[tc] = vals
                col_audit["filled"] = out[tc].notna().sum()
            else:
                out[tc] = None
                if r.source_col:
                    audit["validation"].append(f"'{tc}': source column '{r.source_col}' not found (checked exact + unicode-normalized match).")

        elif r.type == "copy_default":
            default_val = r.value if r.value is not None else ""
            actual_col = find_col(df, r.source_col)
            if actual_col:
                src = df[actual_col]
                def resolve(v):
                    if pd.isna(v) or str(v).strip() == "":
                        col_audit["defaulted"] += 1
                        return default_val
                    v2 = numeric_clean(v) if r.numeric_clean else v
                    v2 = translate_bn_digits(v2) if r.convert_bn_digits else v2
                    return v2
                out[tc] = src.map(resolve)
            else:
                out[tc] = default_val
                col_audit["defaulted"] = n
            col_audit["filled"] = out[tc].notna().sum()

        elif r.type == "batch_id":
            out[tc] = r.value if r.value else None
            if not r.value:
                audit["validation"].append(f"'{tc}' is a batch_id rule with NO value set — this will export blank for every row. Provide the Id from the reference file before shipping.")
            col_audit["filled"] = n if r.value else 0

        elif r.type == "lookup_id":
            actual_col = find_col(df, r.source_col)
            if actual_col:
                vm = lookup_value_maps.get(tc, {})
                def resolve_lookup(v):
                    if pd.isna(v):
                        return None
                    nv = normalize(v)
                    choice = vm.get(nv)
                    if not choice or choice == "-- unmapped --":
                        col_audit["unmapped"] += 1
                        return None
                    return choice.split(" — ")[0]
                out[tc] = df[actual_col].map(resolve_lookup)
                col_audit["filled"] = out[tc].notna().sum()
            else:
                out[tc] = None
                audit["validation"].append(f"'{tc}' is a lookup_id rule with no (valid) source column selected.")

        elif r.type == "generated_sequence":
            width = r.seq_pad
            vals = []
            for i in range(n):
                num = r.seq_start + i
                s = str(num).zfill(width) if width else str(num)
                vals.append(f"{r.seq_prefix}{s}")
            out[tc] = vals
            col_audit["filled"] = n

        elif r.type == "sms_account_number":
            if not r.sms_code:
                audit["validation"].append(f"'{tc}' (SMSAccountNumber) has no pourashava code set — cannot generate.")
                out[tc] = None
            else:
                vals = [f"{r.sms_code}{r.sms_branch}{i}" for i in range(r.seq_start, r.seq_start + n)]
                out[tc] = vals
                if len(set(vals)) != n:
                    audit["validation"].append(f"'{tc}': generated values are NOT all unique — check pourashava code / start value.")
            col_audit["filled"] = out[tc].notna().sum() if out[tc] is not None else 0

        elif r.type == "manual_external":
            actual_col = find_col(df, r.source_col)
            if actual_col:
                out[tc] = df[actual_col]
                col_audit["filled"] = out[tc].notna().sum()
            else:
                out[tc] = None
                audit["validation"].append(f"'{tc}' requires an external process per the SOP (see note) and has no resolved source column yet — exporting blank.")

        elif r.type == "equals_column":
            deferred_equals.append(tc)
            out[tc] = None  # placeholder, filled in second pass
            continue

        elif r.type == "client_id":
            deferred_client_id.append(tc)
            out[tc] = None  # placeholder, filled in second pass
            continue

        audit["columns"][tc] = col_audit

    # second pass: equals_column references another already-computed target column
    for tc in deferred_equals:
        r = rules.get(tc, Rule())
        ref = r.value
        if ref and ref in out.columns:
            out[tc] = out[ref]
            audit["columns"][tc] = {"rule_type": "equals_column", "filled": out[tc].notna().sum(), "defaulted": 0, "unmapped": 0}
        else:
            audit["validation"].append(f"'{tc}' is equals_column but its reference '{ref}' was not found among computed target columns.")
            audit["columns"][tc] = {"rule_type": "equals_column", "filled": 0, "defaulted": 0, "unmapped": 0}

    # second pass: client_id (ClientNo = ward-street-holding, or similar)
    for tc in deferred_client_id:
        r = rules.get(tc, Rule())
        col_audit = {"rule_type": "client_id", "filled": 0, "defaulted": 0, "unmapped": 0, "non_numeric": 0}
        non_numeric_examples = set()

        def resolve_part(mode, source, pad_width, row_idx):
            if mode == "source_column":
                actual = find_col(df, source)
                if not actual:
                    return None, True
                raw = df.at[row_idx, actual]
            elif mode == "lookup_code":
                if source not in out.columns:
                    return None, True
                fk_id = out.at[row_idx, source]
                if fk_id is None or (isinstance(fk_id, float) and pd.isna(fk_id)):
                    return None, True
                code_map = code_lookups.get(source, {})
                raw = code_map.get(str(fk_id))
                if raw is None:
                    return None, True  # FK id had no entry in the Id->Code table
            else:
                return None, True
            return format_code_part(raw, pad_width)

        vals = []
        for idx in df.index:
            w_val, w_ok = resolve_part(r.cid_ward_mode, r.cid_ward_source, r.cid_pad_width, idx)
            s_val, s_ok = resolve_part(r.cid_street_mode, r.cid_street_source, r.cid_pad_width, idx)
            h_val, h_ok = resolve_part(r.cid_holding_mode, r.cid_holding_source, r.cid_pad_width, idx)

            if not w_ok and w_val:
                non_numeric_examples.add(f"ward:{w_val}")
            if not s_ok and s_val:
                non_numeric_examples.add(f"street:{s_val}")
            if not h_ok and h_val:
                non_numeric_examples.add(f"holding:{h_val}")

            if w_val is None or s_val is None or h_val is None:
                vals.append(None)
                col_audit["defaulted"] += 1
            else:
                vals.append(r.cid_separator.join([w_val, s_val, h_val]))
                col_audit["filled"] += 1

        out[tc] = vals
        col_audit["non_numeric"] = len(non_numeric_examples)
        audit["columns"][tc] = col_audit
        if col_audit["defaulted"]:
            audit["validation"].append(f"'{tc}' (client_id): {col_audit['defaulted']} row(s) could not build a full code — missing ward, street, or holding part. Check part configuration and lookup tables.")
        if non_numeric_examples:
            audit["validation"].append(f"'{tc}' (client_id): non-numeric part value(s) found, passed through unpadded — examples: {', '.join(list(non_numeric_examples)[:5])}")

    # ---- SOP-specific validation checks (not generic ETL checks — these
    # are landmines explicitly called out in the instruction doc) ----
    if "ParentId" in out.columns:
        bad = out["ParentId"].apply(lambda v: v not in (None, "", pd.NA)).sum()
        if bad:
            audit["validation"].append(f"ParentId has {bad} non-blank value(s). SOP is explicit: this MUST stay blank — a 0 here breaks front-end display.")

    if "SMSAccountNumber" in out.columns and out["SMSAccountNumber"].notna().any():
        vals = out["SMSAccountNumber"].dropna()
        if vals.duplicated().any():
            audit["validation"].append("SMSAccountNumber has duplicate values — SOP requires uniqueness.")

    if "HoldingType" in out.columns:
        defaulted = audit["columns"].get("HoldingType", {}).get("defaulted", 0)
        if defaulted:
            audit["validation"].append(f"HoldingType defaulted to 3 (non-commercial) for {defaulted} row(s) with no source value — confirm this is acceptable before shipping.")

    if "AnnualValuation" in out.columns and "FinalValuation" in out.columns:
        mismatch = (out["AnnualValuation"].fillna("") != out["FinalValuation"].fillna("")).sum()
        if mismatch:
            audit["validation"].append(f"AnnualValuation != FinalValuation on {mismatch} row(s) — SOP requires these equal.")

    return out, audit
